sudo: required
services:
  - docker

before_install: 
  - docker build -t mena5800/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true mena5800/docker-react npm run test -- --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "eu-west-1"
  app: "fronted"
  env: "Fronted-env"
  bucket_name: "elasticbeanstalk-eu-west-1-975050377735"
  bucket_path: "fronted"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY