sudo: required
services:
  - docker

before_install: 
  - docker build -t mena5800/docker-react -f Dockerfile.dev .

script: 
  - docker run -e CI=true mena5800/docker-react npm run test -- --watchAll=false
